INHERIT: ../base.yml
site_name: "II Encuentro Redi: Creando conexiones – desde el liderazgo hasta la transformación"
site_dir: ../../docs/bloques

plugins:
  - search:
      lang: es

# Page tree
nav:
  - Inicio: index.md
  - Caso 1: caso1.md
  - Caso 2: caso2.md
  - Caso 3: caso3.md
  - Caso 4: caso4.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fpcibersec
      name: Ciberseguridad del IES Alberti en Twitter
